import nodemailer from 'nodemailer';
import { WebClient } from '@slack/web-api';
import Team from '../models/team.js';
import { getAIClient } from '../utils/aiProvider.js';

/**
 * Notification Service
 * Handles weekly summaries via Slack and email with AI-generated insights
 */

// Initialize Slack client
const slackClient = process.env.SLACK_BOT_TOKEN 
  ? new WebClient(process.env.SLACK_BOT_TOKEN)
  : null;

// Initialize email transporter
const emailTransporter = process.env.EMAIL_HOST && process.env.EMAIL_USER
  ? nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT || 587,
      secure: process.env.EMAIL_SECURE === 'true',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD,
      },
    })
  : null;

/**
 * Generate AI-powered weekly summary for a team
 * @param {Object} team - Team document from MongoDB
 */
export async function generateWeeklySummary(team) {
  // If no AI provider configured, use fallback
  if (!process.env.OPENAI_API_KEY && !process.env.ANTHROPIC_API_KEY) {
    return generateFallbackSummary(team);
  }

  const aiClient = getAIClient();
  
  const prompt = `You are a performance management expert. Generate a concise weekly summary for the team "${team.name}".

Current Status:
- Zone: ${team.zone}
- BDI Score: ${team.bdi} (0=excellent, 100=critical burnout)
- 7-day Trend: ${team.trend >= 0 ? '+' : ''}${team.trend}%

Slack Signals:
- Message Volume: ${team.slackSignals?.messageCount || 0} messages
- Avg Response Time: ${team.slackSignals?.avgResponseDelayHours || 0} hours
- Sentiment: ${team.slackSignals?.sentiment || 0}/100

Calendar Signals:
- Meeting Hours: ${team.calendarSignals?.meetingHoursWeek || 0} hours/week
- After-Hours Meetings: ${team.calendarSignals?.afterHoursMeetings || 0}
- Recovery Score: ${team.calendarSignals?.recoveryScore || 0}/100

Generate a 3-paragraph summary:
1. Overall health assessment (2-3 sentences)
2. Key concerns or wins (2-3 bullet points)
3. Recommended actions (2-3 specific suggestions)

Keep it professional, data-driven, and actionable. Use emojis sparingly for visual interest.`;

  try {
    const response = await aiClient.chat.completions.create({
      model: process.env.SUMMARY_MODEL || process.env.OPENAI_MODEL || 'gpt-3.5-turbo',
      messages: [
        { role: 'system', content: 'You are an expert in team performance and burnout prevention.' },
        { role: 'user', content: prompt }
      ],
      max_tokens: 500,
      temperature: 0.7,
    });

    return response.choices[0].message.content.trim();
  } catch (error) {
    console.error('❌ AI summary generation failed:', error.message);
    return generateFallbackSummary(team);
  }
}

/**
 * Fallback summary when AI is unavailable
 */
function generateFallbackSummary(team) {
  const zoneMessages = {
    Recovery: '🟢 Team is in recovery mode with healthy metrics.',
    Stable: '🔵 Team is stable with balanced workload.',
    Watch: '🟡 Team shows early warning signs requiring attention.',
    Surge: '🔴 Team is at high risk of burnout - immediate action needed.',
  };

  return `${zoneMessages[team.zone] || 'Status unknown'}

Current BDI: ${team.bdi}/100 (${team.trend >= 0 ? '+' : ''}${team.trend}% vs last week)

Key Metrics:
• ${team.slackSignals?.messageCount || 0} Slack messages
• ${team.slackSignals?.avgResponseDelayHours || 0}h avg response time
• ${team.calendarSignals?.meetingHoursWeek || 0}h meeting time

Recommendation: Review team workload and meeting schedule to maintain healthy rhythm.`;
}

/**
 * Send weekly summary via Slack
 * @param {string} channelId - Slack channel ID
 * @param {string} teamName - Team name
 * @param {string} summary - AI-generated summary
 */
export async function sendSlackSummary(channelId, teamName, summary) {
  if (!slackClient) {
    console.warn('⚠️  Slack client not configured, skipping Slack notification');
    return false;
  }

  try {
    await slackClient.chat.postMessage({
      channel: channelId,
      text: `📊 Weekly Performance Summary: ${teamName}`,
      blocks: [
        {
          type: 'header',
          text: {
            type: 'plain_text',
            text: `📊 Weekly Summary: ${teamName}`,
            emoji: true,
          },
        },
        {
          type: 'section',
          text: {
            type: 'mrkdwn',
            text: summary,
          },
        },
        {
          type: 'context',
          elements: [
            {
              type: 'mrkdwn',
              text: `Generated by SignalTrue • ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`,
            },
          ],
        },
      ],
    });

    console.log(`✓ Slack summary sent for team: ${teamName}`);
    return true;
  } catch (error) {
    console.error(`❌ Slack send failed for ${teamName}:`, error.message);
    return false;
  }
}

/**
 * Send weekly summary via email
 * @param {string} email - Recipient email
 * @param {string} teamName - Team name
 * @param {string} summary - AI-generated summary
 * @param {Object} team - Full team object for additional data
 */
export async function sendEmailSummary(email, teamName, summary, team) {
  if (!emailTransporter) {
    console.warn('⚠️  Email transporter not configured, skipping email notification');
    return false;
  }

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
    .header { background: linear-gradient(135deg, #6366f1, #a855f7); padding: 30px; text-align: center; color: white; }
    .content { padding: 30px; max-width: 600px; margin: 0 auto; }
    .zone-badge { display: inline-block; padding: 6px 12px; border-radius: 6px; font-weight: bold; margin: 10px 0; }
    .recovery { background: #d1fae5; color: #065f46; }
    .stable { background: #dbeafe; color: #1e40af; }
    .watch { background: #fef3c7; color: #92400e; }
    .surge { background: #fee2e2; color: #991b1b; }
    .metrics { background: #f9fafb; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .metric-row { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #e5e7eb; }
    .footer { text-align: center; padding: 20px; color: #6b7280; font-size: 14px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 Weekly Performance Summary</h1>
    <h2>${teamName}</h2>
  </div>
  <div class="content">
    <div class="zone-badge ${team.zone.toLowerCase()}">${team.zone} Zone</div>
    
    <div class="metrics">
      <div class="metric-row">
        <strong>BDI Score:</strong>
        <span>${team.bdi}/100</span>
      </div>
      <div class="metric-row">
        <strong>7-Day Trend:</strong>
        <span>${team.trend >= 0 ? '+' : ''}${team.trend}%</span>
      </div>
      <div class="metric-row">
        <strong>Messages:</strong>
        <span>${team.slackSignals?.messageCount || 0}</span>
      </div>
      <div class="metric-row">
        <strong>Meeting Hours:</strong>
        <span>${team.calendarSignals?.meetingHoursWeek || 0}h/week</span>
      </div>
      <div class="metric-row">
        <strong>Recovery Score:</strong>
        <span>${team.calendarSignals?.recoveryScore || 0}/100</span>
      </div>
    </div>

    <div style="white-space: pre-line; line-height: 1.8;">
      ${summary}
    </div>
  </div>
  <div class="footer">
    Generated by SignalTrue on ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
  </div>
</body>
</html>
  `;

  try {
    await emailTransporter.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to: email,
      subject: `📊 Weekly Summary: ${teamName}`,
      html: htmlContent,
      text: summary, // Fallback plain text
    });

    console.log(`✓ Email summary sent to ${email} for team: ${teamName}`);
    return true;
  } catch (error) {
    console.error(`❌ Email send failed for ${teamName}:`, error.message);
    return false;
  }
}

/**
 * Send weekly summaries for all teams
 * @param {Object} options - Configuration options
 */
export async function sendWeeklySummaries(options = {}) {
  const { includeSlack = true, includeEmail = true } = options;
  
  const teams = await Team.find({});
  console.log(`📧 Sending weekly summaries for ${teams.length} teams...`);

  for (const team of teams) {
    try {
      // Generate AI summary
      const summary = await generateWeeklySummary(team);

      // Send to Slack
      if (includeSlack && team.slackChannelId) {
        await sendSlackSummary(team.slackChannelId, team.name, summary);
      }

      // Send to email (if configured in env or team has email field)
      if (includeEmail && process.env.NOTIFICATION_EMAIL) {
        await sendEmailSummary(
          process.env.NOTIFICATION_EMAIL,
          team.name,
          summary,
          team
        );
      }
    } catch (error) {
      console.error(`❌ Summary send failed for ${team.name}:`, error.message);
    }
  }

  console.log('✅ All weekly summaries sent');
}

export default {
  generateWeeklySummary,
  sendSlackSummary,
  sendEmailSummary,
  sendWeeklySummaries,
};
