import mongoose from 'mongoose';


const teamSchema = new mongoose.Schema({
  name: { type: String, required: true },
  orgId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'Organization',
    required: true 
  },
  zone: { type: String, enum: ['Recovery', 'Stable', 'Watch', 'Surge'], default: 'Stable' },
  bdi: { type: Number, default: 50 },
  trend: { type: Number, default: 0 }, // percent change (calculated from history)
  favorite: { type: Boolean, default: false },

  // Baseline for comparison
  baseline: {
    bdi: { type: Number },
    date: { type: Date },
    signals: {
      slack: { type: Object },
      calendar: { type: Object }
    }
  },

  // Seasonality flags (e.g., summer, q4, etc.)
  seasonalityFlags: {
    type: Object,
    default: {}
  },

  // Driver weights for BDI decomposition
  driverWeights: {
    type: Object,
    default: {}
  },

  // Historical BDI snapshots (most recent first)
  bdiHistory: [{
    bdi: { type: Number, required: true },
    timestamp: { type: Date, default: Date.now },
    slackSignals: {
      messageCount: { type: Number },
      avgResponseDelayHours: { type: Number },
      sentiment: { type: Number }
    },
    calendarSignals: {
      meetingHoursWeek: { type: Number },
      afterHoursMeetings: { type: Number },
      recoveryScore: { type: Number }
    }
  }],

  // Current Signals
  slackSignals: {
    messageCount: { type: Number, default: 0 },
    avgResponseDelayHours: { type: Number, default: 0 },
    sentiment: { type: Number, default: 0 },
  },
  calendarSignals: {
    meetingHoursWeek: { type: Number, default: 0 },
    afterHoursMeetings: { type: Number, default: 0 },
    recoveryScore: { type: Number, default: 0 },
  },

  // Slack channel ID for integration
  slackChannelId: { type: String },

  // Google Calendar ID for integration
  calendarId: { type: String },

  // Optional playbook generated by OpenAI
  playbook: { type: String, default: '' },
}, { timestamps: true });

export default mongoose.model('Team', teamSchema);
